[package]
name = "openshmem-benchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
ctrlc = "3.4.5"
openshmem-sys = { git = "https://github.com/taooceros/openshmem-sys.git" }
